Gitignore
OlenaHatala/Team-project pull request #19
Opened 2023-02-24 11:46 UTC by OlenaHatala

Create only one .gitignore file in a root folder

2023-02-24 11:48 UTC, ayatsuliak approved these changes

2023-02-25 10:44 UTC, daftkid requested changes

2023-02-25 10:44 UTC, daftkid commented on .gitignore
> +
Do you still have them in place? I did not see any mentions of them in the readme

2023-03-03 17:32 UTC, OlenaHatala commented on .gitignore
> +
you're correct, those lines were removed from gitignore

2023-03-04 13:04 UTC, daftkid approved these changes

2023-03-04 14:11 UTC, merged