Taken tickets page
OlenaHatala/Team-project pull request #24
Opened 2023-03-06 17:13 UTC by AndriyKap

2023-03-06 17:26 UTC, ishandry approved these changes

2023-03-06 17:33 UTC, ishandry requested changes
Inappropriate change was found inside of a file, that has no relations with the feature branch.

2023-03-06 17:33 UTC, ishandry commented on front-end/frontend/src/components/newboard/NewBoardForm.js
> -  const navigate = useNavigate();
?

2023-03-06 17:36 UTC, ishandry approved these changes

2023-03-07 18:24 UTC, daftkid requested changes

2023-03-07 18:24 UTC, daftkid commented on front-end/frontend/src/components/takenTickets/DefaultTickets.js
> +{id: 8, boardName: "Andrii's Barbershop", date: "23.04.2023", time: "14:00", status: "confirmed"}]
Can it be added to DB instead of mocking it on the Frontend part? do you want this code to be packaged for production so all users will have this for them?

2023-03-29 14:30 UTC, closed without merging