Board list
OlenaHatala/Team-project pull request #28
Opened 2023-03-20 17:27 UTC by AndriyKap

2023-03-20 17:38 UTC, ishandry approved these changes

2023-03-20 17:39 UTC, OlenaHatala approved these changes

2023-03-20 17:41 UTC, daftkid requested changes

2023-03-20 17:41 UTC, daftkid commented on front-end/frontend/src/modules/boards/components/table_info/TableInfo.js
> +      <span className={classes["calendar-icon"]}><Icon icon={calendar} size={50} style={{ color: '#1C1333' }}/></span>
This value of the color is repeatedly in use within different files. Does it make sense to have it defined in some global CSS file?

2023-03-20 17:41 UTC, daftkid commented on front-end/frontend/src/modules/boards/components/table_info/TableInfo.js
> +        <span className={classes["circleRight-icon"]}><Icon icon={circleRight} size={36} style={{ color: '#717171' }}/></span>
The same situation here

2023-04-05 17:20 UTC, daftkid requested changes

2023-04-05 17:20 UTC, daftkid commented on front-end/frontend/src/modules/boards/components/board_list/BoardList.module.css
> +
I neeeeeed more space!!!

2023-04-14 17:52 UTC, daftkid requested changes

2023-04-14 17:52 UTC, daftkid commented on front-end/frontend/src/modules/common/hooks/index.js
why is this empty?

2023-04-17 14:55 UTC, ishandry commented on front-end/frontend/src/modules/common/hooks/index.js
fixed

2023-04-18 06:58 UTC, daftkid requested changes

2023-04-18 06:58 UTC, daftkid commented on front-end/frontend/src/modules/home/pages/HomeIndexPage/HomeIndexPage.module.css
This one is still empty :)

2023-04-20 16:08 UTC, merged